name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run TIMESTAMP=$(date +%s)
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build --tag dyrits/docker-react:$TIMESTAMP .
      - run: docker run -e CI=true dyrits/docker-react:$TIMESTAMP npm test