name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - id: build
        run: |
          docker build --tag dyrits/docker-react .
          docker push dyrits/docker-react

  test:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker run -it dyrits/docker-react:latest npm test
